### ISSUE TITLE
Simplify CLI.

### ISSUE THREAD

**Issue by itsjohncs** [itsjohncs/superzippy#21]
Users should be able to point Super Zippy at a file or directory and have Super Zippy transform it into a Super Zip automatically.

**Comment by brownhead** [comment]
I think this is vital to make this tool worthwhile. The overhead of making a `setup.py` file is honestly too great.

**Comment by brownhead** [comment]
Alright, so I already had a way to raw copy into the superzip. That should probably just be the default. You can point it at a directory or file and it'll just copy that directory into the `superzip`. That'll make it so you can run `superzippy mypkg` and have it just work. I can omit `.pyc` files by default, and it'll be fine.

If you want to install packages or dependenices, you can do `superzippy -r requirements.txt mypkg` and that'll just work too, or `superzippy -p clint mypkg` if clint is your only dependency.

This'll break the current API (because previously if you ran `superzippy .` it'd try to pip install the current directory, whereas now it'll copy it, but users can now do `superzippy -p .` and it'll work). I hope breaking the API is OK. Unfortunately I don't have a sense of the userbase that superzippy has, if it has any.

That's actually something I could probably try to correct. Some kind of mailing list would be good...
