### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by zrks** [itsjohncs/superzippy#33]
On fresh superzippy install (python version: 3.6.7, pip version: 18.1; superzippy==0.0.9):
```
(test-venv) marcis@marcis$ superzippy . slimdown.slimdown:cli
Traceback (most recent call last):
  File ".../test-venv/bin/superzippy", line 7, in <module>
    from superzippy.packaging import run
  File ".../test-venv/lib/python3.6/site-packages/superzippy/packaging.py", line 296
    os.chmod(output_file, 0755)
                             ^
SyntaxError: invalid token
```

**Comment by itsjohncs** [comment]
Thanks for the clear bug report. I haven't touched this project in a long time, so I don't know that I'll get around to making a fix for this unfortunately (not saying I won't, it's certainly tempting...). My experience with Python is almost entirely in 2.x so testing a 3.x specific fix isn't going to be the quickest thing for me.

But if you'd like to make a fix at least locally it looks like `0755` just needs to be changed to `0o755`. If that bug is in there though, it's likely there'll be more 3.x bugs.

You can also try the latest version on git, which might be more recent.
